name: Docker

on:
  push:
    branches:
      - master
env:
  TAG: ${{ secrets.DOCKERHUB_USERNAME }}/tgs-to-gif:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and load
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ${{ env.TAG }}
      - name: Test
        run: |
          docker run --rm -e FORMAT=gif -v $(pwd)/stickers:/source ${{ env.TAG }}
          docker run --rm -e FORMAT=png -v $(pwd)/stickers:/source ${{ env.TAG }}
          docker run --rm -e FORMAT=apng -v $(pwd)/stickers:/source ${{ env.TAG }}
          docker run --rm -e FORMAT=webp -v $(pwd)/stickers:/source ${{ env.TAG }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/x86_64
          push: true
          tags: ${{ env.TAG }}
