name: Docker

on:
  push:
  workflow_dispatch:
env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/tgs-to-gif

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and load
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: ${{ env.IMAGE }}
      - name: Test
        run: |
          docker run --rm -e FORMAT=gif -v $(pwd)/stickers:/source ${{ env.IMAGE }}
          docker run --rm -e FORMAT=png -v $(pwd)/stickers:/source ${{ env.IMAGE }}
          docker run --rm -e FORMAT=apng -v $(pwd)/stickers:/source ${{ env.IMAGE }}
          docker run --rm -e FORMAT=webp -v $(pwd)/stickers:/source ${{ env.IMAGE }}
      - name: Build and push latest
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          platforms: linux/x86_64
          push: true
          tags: ${{ env.IMAGE }}:latest
      - name: Build and push tag
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v3
        with:
          platforms: linux/x86_64
          push: true
          tags: ${{ env.IMAGE }}:${{ github.ref_name }}
